# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='template',
            field=models.BooleanField(default=False),
        ),
    ]
