# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wallet_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.CharField(default='example wallet', max_length=100),
            preserve_default=False,
        ),
    ]
