# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171015_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='result',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
