# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 19:25
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171016_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='closed',
        ),
        migrations.AddField(
            model_name='event',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='chosen_result',
            field=models.IntegerField(choices=[(0, 'X'), (1, '1'), (2, '2')], verbose_name='Typowany wynik'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Czas utworzenia'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Event', verbose_name='Typowane wydarzenie'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='odd',
            field=models.FloatField(verbose_name='Kurs zakładu'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Zakład nierozliczony'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='reward',
            field=models.FloatField(verbose_name='Możlwa wygrana'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, 'Wartość zakładu nie może być ujemna!')], verbose_name='Stawka zakładu'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Wallet', verbose_name='Portfel'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='won',
            field=models.NullBooleanField(verbose_name='Zakład wygrany'),
        ),
        migrations.AlterField(
            model_name='event',
            name='away_odd',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1.0, 'Minimalny kurs wynosi 1.0.')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='draw_odd',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1.0, 'Minimalny kurs wynosi 1.0.')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='home_odd',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1.0, 'Minimalny kurs wynosi 1.0.')]),
        ),
    ]
