# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 20:43
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171028_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('can_close', 'Can insert result and close event.'),)},
        ),
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor wydarzenia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='away_name',
            field=models.CharField(max_length=50, verbose_name='Nazwa zespołu gości'),
        ),
        migrations.AlterField(
            model_name='event',
            name='away_odd',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1.0, 'Minimalny kurs wynosi 1.0.')], verbose_name='Kurs na zwycięstwo gości'),
        ),
        migrations.AlterField(
            model_name='event',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Czas utworzenia wydarzenia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis wydarzenia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='draw_odd',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1.0, 'Minimalny kurs wynosi 1.0.')], verbose_name='Kurs na remis'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(verbose_name='Czas zakończenia wydarzenia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='home_name',
            field=models.CharField(max_length=50, verbose_name='Nazwa zespołu gospodarzy'),
        ),
        migrations.AlterField(
            model_name='event',
            name='home_odd',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1.0, 'Minimalny kurs wynosi 1.0.')], verbose_name='Kurs na zwycięstow gospodarzy'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa wydarzenia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Wydarzenie nierozliczone'),
        ),
        migrations.AlterField(
            model_name='event',
            name='result',
            field=models.IntegerField(blank=True, choices=[(0, 'X'), (1, '1'), (2, '2')], null=True, verbose_name='Wynik wydarzenia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(verbose_name='Czas rozpoczęcia wydarzenia'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Portfel jest aktywny'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Czas utworzenia'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis portfela'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='money',
            field=models.FloatField(verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa portfela'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Właściciel portfela'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='template',
            field=models.BooleanField(default=False, verbose_name='Portfel-szablon'),
        ),
    ]
